// src/services/offerValidator.js
// Reviews a generated offer pack before it goes out.
// Checks quality criteria and saves validated offers to data/offers/validated/

import fs from "fs";
import path from "path";

const VALIDATED_DIR = path.join("data", "offers", "validated");

// Price ranges we consider reasonable (in USD/CAD)
const PRICE_MIN = 100;
const PRICE_MAX = 5000;

// ─── Checks ───────────────────────────────────────────────────────────────────

function extractPriceNumbers(priceStr) {
  const matches = String(priceStr || "").match(/\d{2,}/g) || [];
  return matches.map(Number);
}

/**
 * Validates a pack generated by packGenerator.js.
 * Returns { valid: boolean, issues: string[], warnings: string[] }
 */
export function validateOffer(pack) {
  const issues = [];
  const warnings = [];

  if (!pack) {
    return { valid: false, issues: ["pack is null or undefined"], warnings };
  }

  // 1. Must have a leadId
  if (!pack.leadId) {
    issues.push("Missing leadId — cannot trace offer back to a lead");
  }

  // 2. Must reference a clinic/business name
  const tailoredFor = pack.offer?.tailoredFor || "";
  if (!tailoredFor || tailoredFor.toLowerCase() === "your business") {
    warnings.push("Offer is not personalized to a specific clinic name");
  }

  // 3. Must have a pain summary
  if (!pack.painSummary || pack.painSummary.length < 20) {
    issues.push("Pain summary is missing or too short (< 20 chars)");
  }

  // 4. Must have exactly 3 tiers
  const tiers = pack.offer?.tiers || [];
  if (tiers.length !== 3) {
    issues.push(`Expected 3 offer tiers, got ${tiers.length}`);
  }

  // 5. Each tier must have a name, price, deliverables, and result
  for (let i = 0; i < tiers.length; i++) {
    const t = tiers[i];
    const label = `Tier ${i + 1} (${t.name || "unnamed"})`;

    if (!t.name) issues.push(`${label}: missing name`);
    if (!t.price) issues.push(`${label}: missing price`);
    if (!Array.isArray(t.deliverables) || t.deliverables.length === 0) {
      issues.push(`${label}: no deliverables listed`);
    }
    if (!t.expectedResult) warnings.push(`${label}: no expected result stated`);

    // 6. Price sanity check
    const prices = extractPriceNumbers(t.price);
    if (prices.length > 0) {
      const min = Math.min(...prices);
      const max = Math.max(...prices);
      if (min < PRICE_MIN) warnings.push(`${label}: price $${min} seems too low`);
      if (max > PRICE_MAX) warnings.push(`${label}: price $${max} seems too high`);
    } else {
      warnings.push(`${label}: price field has no numeric value`);
    }
  }

  // 7. Must have next actions
  if (!Array.isArray(pack.nextActions) || pack.nextActions.length === 0) {
    warnings.push("No nextActions defined");
  }

  const valid = issues.length === 0;
  return { valid, issues, warnings };
}

/**
 * Validates a pack and saves it to data/offers/validated/ if it passes.
 * If it fails, logs the issues and saves to data/offers/rejected/ for review.
 *
 * @param {Object} pack - from packGenerator.generatePackForLead()
 * @returns {{ valid: boolean, issues: string[], warnings: string[], savedPath: string|null }}
 */
export function saveValidatedOffer(pack) {
  const result = validateOffer(pack);
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const leadId = (pack?.leadId || "unknown").slice(0, 20);
  const filename = `offer_${leadId}_${ts}.json`;

  const outData = { ...pack, validation: result, savedAt: new Date().toISOString() };

  if (result.valid) {
    const outPath = path.join(VALIDATED_DIR, filename);
    fs.mkdirSync(VALIDATED_DIR, { recursive: true });
    fs.writeFileSync(outPath, JSON.stringify(outData, null, 2), "utf-8");
    result.savedPath = outPath;
    console.log(`✓ Offer validated → ${outPath}`);
  } else {
    const rejectedDir = path.join("data", "offers", "rejected");
    const rejectedPath = path.join(rejectedDir, filename);
    fs.mkdirSync(rejectedDir, { recursive: true });
    fs.writeFileSync(rejectedPath, JSON.stringify(outData, null, 2), "utf-8");
    result.savedPath = null;
    console.warn(`⚠ Offer failed validation → ${rejectedPath}`);
    result.issues.forEach((i) => console.warn(`  ✗ ${i}`));
  }

  if (result.warnings.length > 0) {
    result.warnings.forEach((w) => console.warn(`  ⚠ ${w}`));
  }

  return result;
}
